export const foundDirectCompetitors = [
  'Selenium',
  'Appium',
  'Micro Focus UFT One',
  'Tricentis Tosca',
  'TestComplete',
  'ReadyAPI',
  'LambdaTest',
  'BrowserStack',
  'Sauce Labs',
  'TestGrid',
  'WebdriverIO',
  'Tricentis Testim',
  'Micro Focus Silk Test',
  'Robot Framework',
  'Playwright',
  'Applitools',
  'TestDrive',
  'ACCELQ',
  'mabl',
  'TestProject',
  'Opkey',
  'Endtest',
  'Testinium',
  'VisualTest',
  'Qualibrate',
  'QMetry Digital Quality Platform',
  'walrus.ai',
  'CloudQA',
  'TestArchitect',
  'SmartMeter.io',
  'Runscope',
  'Usetrace',
  'Monkey Test It',
  'Subject7',
  'AppLoader',
  'QF-Test',
  'UXprobe',
  'Test Lodge',
  'Boozang',
  'UbikLoadPack',
  'testomat.io',
  'MockLab',
  'Sahi Pro',
  'Sofy.ai',
  'Maveryx',
  'Spirent iTest',
  'Eggplant Digital Automation Intelligence',
  'Test Modeller',
  'MuukTest',
  'QMetry Automation Studio',
  'BugBug',
  'Virtuoso',
  'Functionize',
  'Assertible',
  'Witbe QoE Monitoring Robots',
  'Frugal Testing',
  'TestResults.io',
  'Degust',
  'Testpad',
  'Automatur',
  'devmate',
  'BI Validator',
  'Testdriver Cloud Edition',
  'Orangebeard',
  'DogQ',
  'Codified Security',
  'Testlauncher',
  'Verifaya Studio',
  'QMetry Test Manager',
  'Gatling Enterprise',
  'VectorCAST',
  'HyperTest',
  'TPT',
  'Validify',
  'AutomQA',
  'Symflower',
  'steadybit',
  'BotPlay Automation',
  'Cerberus',
  'Quality Management Tool',
  'SoftwareTesting.AI',
  'Bellatrix',
  'GigaFox',
  'Time Machine',
  'HorusTest',
  'MarathonITE',
  'eureQa',
  'testOFFICE',
  'ReTest',
  'Axe',
  'InformUp Tracking System',
  'QACoverage',
  'Qsome Software Testing Tool',
  'TEST ACE',
  'Tenjin Online',
  'Testup',
  'Mr Suricate',
  'Multibrowser',
  'AutonomIQ',
  'co.meta',
  'AttackForge',
  'DigyKube',
  'Gridlastic',
  'Eyerobot',
  'AppDoctor',
  'UXRecord',
  'Touca',
  'IQM Studio',
  'motel.io',
  'TestCenter',
  'Behavior Driven Test Robot',
  'QATTS',
  'autoMagiQ',
  'testRigor',
  'DataKitchen DataOps Platform',
  'QATouch',
  'Zeuz',
  'Autify',
  'Figaf IRT',
  'Hammer Cloud Platform',
  'Polarion QA',
  'ETL Validator',
  'Applied Intuition',
  'Tricentis Test Automation',
  'LEAPWORK',
  'Synopsys TestMAX',
  'Int4 IFTT',
  'Qyrus',
  'TestingWhiz',
  'Diffy',
  'ProdPerfect',
  'iCEDQ',
  'EarlGrey',
  'Perfecto',
  'AutomatePro',
  'Allure TestOps',
  'Appvance IQ',
  'Zebrunner',
  'Testsigma',
  'TestCafe',
  'Citrus Framework',
  'Provar',
  'Perfecto Scriptless',
  'Bootstrap',
  'CloudTestr',
  'Behave',
  'Cucumber Open',
  'REST Assured',
  'OpenTest',
  'Rainforest QA',
];
