export const foundCompetitors = [
  'BrowserStack',
  'Sauce Labs',
  'Selenium',
  'ReadyAPI',
  'LambdaTest',
  'TestComplete',
  'Micro Focus UFT One',
  'Tricentis Tosca',
  'Appium',
  'BlazeMeter',
  'HeadSpin',
  'Perfecto by Perforce',
  'ignio AIOps',
  'Worksoft',
  'Tricentis Test Automation for Salesforce',
  'TestGrid',
  'WebdriverIO',
  'Kobiton',
  'Tricentis Testim',
  'Testlio',
  'Micro Focus Silk Test',
  'Robot Framework',
  'Playwright',
  'FitNesse',
  'BMC AMI DevX',
  'Applitools',
  'MOZARK',
  'Eggplant, from Keysight',
  'TestDrive',
  'SBOX',
  'SpecFlow',
  'ACCELQ',
  'TestingBot',
  'AutomationHQ',
  'mabl',
  'TestProject',
  'Avo Assure',
  'SystemLink',
  'Opkey',
  'NoCodeBDD',
  'Tigmat',
  'Endtest',
  'Rainforest',
  'Deque',
  'Terapeak Research',
  'CloudBeat',
  'Preflight',
  'Goinsta.ai (Powered by Cigniti)',
  'UP9',
  'Testinium',
  'VisualTest',
  'Qualibrate',
  'QMetry Digital Quality Platform',
  'VATT - Vuram Automation Testing Tool',
  'walrus.ai',
  'Frameium by Testhouse',
  'DotWalk',
  'CloudQA',
  'Hughes Systique UTAF',
  'TestArchitect',
  'SmartMeter.io',
  'Quality Clouds',
  'Runscope',
  'Usetrace',
  'Monkey Test It',
  'Subject7',
  'AppLoader',
  'Batch Images',
  'UserTest.io',
  'QF-Test',
  'AttackFlow',
  'Omnicontext',
  'UXprobe',
  'Test Lodge',
  'Boozang',
  'Testifi',
  'UbikLoadPack',
  'testomat.io',
  'Taplytics',
  'Stack Moxie',
  'MockLab',
  'algoQA',
  'Sahi Pro',
  'Sofy.ai',
  'Maveryx',
  'Spirent iTest',
  'Eggplant Digital Automation Intelligence',
  'Test Modeller',
  'MuukTest',
  'QMetry Automation Studio',
  'BugBug',
  'Virtuoso',
  'Moropo',
  'Omnium Lite',
  'CI FUZZ',
  'STBSuite',
  'Functionize',
  'Alithya GoTest',
  'Test Evolve',
  'Assertible',
  'Witbe QoE Monitoring Robots',
  'Frugal Testing',
  'TestResults.io',
  'Degust',
  'Intelligent Testing and Digital Assurance Services',
  'VisWiz.io',
  'Testpad',
  'Automatur',
  'Doppelio',
  'devmate',
  'QaTraq',
  'BI Validator',
  'Testdriver Cloud Edition',
  'Orangebeard',
  'DogQ',
  'Codified Security',
  'AdParlor',
  'Imagium',
  'Testlauncher',
  'Verifaya Studio',
  'suxxesso Tool Suite',
  'PadiAct',
  'QMetry Test Manager',
  'Gatling Enterprise',
  'Meeshkan',
  'Chronos Workflow',
  'Appsurify',
  'VectorCAST',
  'HyperTest',
  'Trudon',
  'TPT',
  'Validify',
  'AutomQA',
  'steadybit',
  'Symflower',
  'Signadot',
  'BotPlay Automation',
  'Enchatted',
  'Cerberus',
  'Quality Management Tool',
  'SoftwareTesting.AI',
  'Bellatrix',
  'GigaFox',
  'neuralg8',
  'Time Machine',
  'HorusTest',
  'MarathonITE',
  'VIZOR License Manager',
  'eureQa',
  'testOFFICE',
  'ReTest',
  'Axe',
  'Nineteen68',
  'InformUp Tracking System',
  'QACoverage',
  'Infosys Validation Solutions',
  'MyCrowd QA',
  'Qsome Software Testing Tool',
  'WonderProxy',
  'TEST ACE',
  'Tenjin Online',
  'Testup',
  'Mr Suricate',
  'Multibrowser',
  'Drone',
  'Idelium',
  'AutonomIQ',
  'co.meta',
  'AttackForge',
  'DigyKube',
  'Gridlastic',
  'Eyerobot',
  'Garden',
  'AppDoctor',
  'UXRecord',
  'Touca',
  'IQM Studio',
  'motel.io',
  'TestCenter',
  'Behavior Driven Test Robot',
  'QATTS',
  'autoMagiQ',
  'testRigor',
  'DataKitchen DataOps Platform',
  'QATouch',
  'Zeuz',
  'Autify',
  'Figaf IRT',
  'Hammer Cloud Platform',
  'Polarion QA',
  'ETL Validator',
  'Applied Intuition',
  'Tricentis Test Automation',
  'LEAPWORK',
  'Synopsys TestMAX',
  'Int4 IFTT',
  'Qyrus',
  'TestingWhiz',
  'Diffy',
  'ProdPerfect',
  'iCEDQ',
  'EarlGrey',
  'Perfecto',
  'AutomatePro',
  'Allure TestOps',
  'Appvance IQ',
  'Zebrunner',
  'Testsigma',
  'TestCafe',
  'Citrus Framework',
  'Provar',
  'Perfecto Scriptless',
  'Bootstrap',
  'CloudTestr',
  'Behave',
  'Cucumber Open',
  'REST Assured',
  'OpenTest',
  'Rainforest QA',
];
