export const foundDirectCompetitors = [
  'LambdaTest',
  'Ranorex Studio',
  'TestRail',
  'SoapUI',
  'BrowserStack',
  'TestProject',
  'Cypress',
  'Leapwork',
  'Endtest',
  'ACCELQ',
  'mabl',
  'MagicPod',
  'Sauce Labs',
  'HeadSpin',
  'Applitools',
  'Test Modeller',
  'qTest',
  'ALM/Quality Center',
  'Eggplant Test',
  'TestComplete',
  'Perfecto',
  'Ghost Inspector',
  'Qase',
  'Sahi Pro',
  'TestingBot',
  'TestCafe',
  'Testlio',
  'Testim',
  'Tricentis Tosca',
  'UFT (formerly HP QTP)',
  'Zephyr Enterprise',
  'PractiTest',
  'Selenium',
];
