export const foundCompetitors = [
  'LambdaTest',
  'Ranorex Studio',
  'TestRail',
  'SoapUI',
  'BrowserStack',
  'Codemagic',
  'SpiraTest',
  'CircleCI',
  'mabl',
  'Cypress',
  'MagicPod',
  'TestProject',
  'Leapwork',
  'Endtest',
  'Testim',
  'ACCELQ',
  'Tuskr',
  'Cerberus',
  'HeadSpin',
  'Applitools',
  'Sauce Labs',
  'Qualibrate',
  'Provar',
  'ElectroNeek Platform',
  'aqua',
  'Test Modeller',
  'qTest',
  'TestCaseLab',
  'UsableNet AQA',
  'ALM/Quality Center',
  'Kobiton',
  'TestMonitor',
  'eureQa',
  'Kualitee',
  'CloudQA',
  'AppLoader',
  'Subject7',
  'Allure TestOps',
  'Agilitest',
  'Eggplant Test',
  'ProdPerfect',
  'BlazeMeter',
  'Tricentis Tosca',
  'Rainforest',
  'testomat.io',
  'Usetrace',
  'Loadium',
  'Rapise',
  'Testsigma',
  'Zephyr Enterprise',
  'pCloudy',
  'PractiTest',
  'Perfecto',
  'Loadero',
  'ZeuZ',
  'Mailosaur',
  'Ghost Inspector',
  'Mr Suricate',
  'Qase',
  'Cyara',
  'Sahi Pro',
  'Qualitia',
  'TestingBot',
  'Karate Labs',
  'Boozang',
  'TestFirst',
  'Screenster',
  'Sofy',
  'TestingWhiz',
  'Testifi',
  'Incredibuild',
  'Ubertesters',
  'TestStand',
  'Maveryx',
  'T-Plan',
  'test IO',
  'UbikLoadPack',
  'Zebrunner',
  'Test Lodge',
  'Xray',
  'TestComplete',
  'QF-Test',
  'Testnetic',
  'QMetry',
  'testRigor',
  'Zephyr Squad',
  'Opkey',
  'Testuff',
  'Polarion QA',
  'Browserling',
  'Gatling Enterprise',
  'TestCafe',
  'WebLOAD',
  'Applause',
  'Bellatrix',
  'CARINA',
  'CucumberStudio',
  'DogQ',
  'Functional Test Automation',
  'MarathonITE',
  'QATTS',
  'ReTest',
  'Test Evolve',
  'Testlio',
  'Testpad',
  'Worksoft Certify',
  'Digital.ai Continuous Testing',
  'Ghostlab',
  'Parasoft SOAtest',
  'QATouch',
  'TestArchitect',
  'TestCenter',
  'TestDrive',
  'Testersuite',
  'Tricentis Test Automation',
  'Katalon TestOps',
  'Autify',
  'Functionize',
  'Test Automation for ServiceNow',
  'Testinium',
  'Testlauncher',
  'TestMagic',
  'testmail.app',
  'Virtuoso',
  'Zephyr Scale',
];
