chromiumBinary: C:\Program Files\Google\Chrome\Application\chrome.exe
chromiumProfile: D:\workspace\katalon-toolbox\packages\extension\profiles\default
startUrl: # from --start-url
  - https://chat.openai.com/
