chromiumBinary: C:\Program Files\Google\Chrome\Application\chrome.exe
chromiumProfile: D:\workspace\growth-toolkit\packages\extension\profiles\default
startUrl: # from --start-url
  - https://chat.openai.com/
