export const foundCompetitors = [
  'Tricentis NeoLoad',
  'LambdaTest',
  'Tricentis Tosca',
  'OpenText UFT One',
  'Automate',
  'Tricentis TestProject (Legacy)',
  'Eggplant Digital Automation Intelligence',
  'SmartBear ReadyAPI',
  'Parasoft SOAtest',
  'Visual Studio Test Professional',
  'Tricentis qTest',
  'Parasoft C/C++test',
  'UiPath Business Automation Platform',
  'Worksoft Certify',
  'SmartBear TestComplete',
  'Telerik Test Studio',
  'ACCELQ Unified',
  'Digital.ai Continuous Testing',
  'TestDrive',
  'Rational Functional Tester',
  'Squish',
  'Tricentis Testim',
  'App Automate',
  'Parasoft Jtest',
  'Applitools',
  'OpenText UFT Digital Lab',
  'Opkey',
  'Perfecto Platform',
  'Copado Robotic Testing',
  'AscentialTest',
  'Functionize',
  'LEAPWORK Test Automation',
  'Codeless Automated Testing',
  'QMetry Automation Studio',
  'Sauce Labs Continuous Testing Cloud',
  'Rational Integration Tester (Legacy)',
  'OpenText UFT Developer',
  'ZAPTEST',
  'Appvance IQ',
  'Rational Test Workbench',
  'Qualitia',
  'Mabl',
  'HeadSpin Platform',
  'Avo Assure',
  'Subject7',
  'Virtual Cloud',
  'Rapise',
  'axe DevTools',
  'Beagle Security',
  'CI Fuzz',
  'Int4 Suite',
  'Eyes',
  'Flexib+',
  'Virtuoso',
  'testRigor',
];
