export const foundDirectCompetitors = [
  'Tricentis Tosca',
  'Automate',
  'Eggplant Digital Automation Intelligence',
  'SmartBear TestComplete',
  'ACCELQ Unified',
  'Rational Functional Tester',
  'Tricentis Testim',
  'Perfecto Platform',
  'Functionize',
  'LEAPWORK Test Automation',
  'Codeless Automated Testing',
  'QMetry Automation Studio',
  'Sauce Labs Continuous Testing Cloud',
  'OpenText UFT Developer',
  'ZAPTEST',
  'Appvance IQ',
  'Mabl',
  'Virtuoso',
  'testRigor',
];
