export const foundCompetitors = [
  'LambdaTest',
  'Keysight Eggplant',
  'Test IO',
  'QA Wolf',
  'Provar',
  'Leapwork',
  'Opkey',
  'Testlio',
  'Rainforest QA',
  'Tricentis Tosca',
  'Applitools',
  'pCloudy',
  'Sauce Labs',
  'Tricentis qTest',
  'Virtuoso',
  'Micro Focus UFT One',
  'Semaphore',
  'Testsigma',
  'ContextQA',
  'SOAPUI',
  'TestStand',
  'testomat.io',
  'Qase',
  'Apache JMeter',
  'iMacros',
  'Perfecto',
  'Cyara Platform',
  'Avo Assure',
  'Oracle Application Testing Suite',
  'Worksoft Certify',
  'Copado Robotic Testing',
  'Endtest',
  'TestComplete',
  'Tricentis Testim',
  'Ghost Inspector',
  'Loadmill',
  'Reflect',
  'HeadSpin',
  'TestProject',
  'Functionize',
  'ACCELQ',
  'Micro Focus LoadRunner Professional',
  'QMetry Test Management',
  'ReadyAPI',
  'AutomatePro',
  'BiG EVAL',
  'Micro Focus UFT Developer',
  'Telerik Test Studio',
  'SeeTest: Testing Platform for Web & Mobile Apps',
  'QA Touch',
  'mabl',
  'Ranorex Studio',
  'HyperTest',
  'testRigor AI-powered Automation Testing Tool',
  'Subject7',
  'IBM Engineering Test Management',
  'TestingWhiz',
  'TestCafe',
  'Preflight',
  'ProdPerfect',
  'Zephyr Enterprise',
  'Stack Moxie',
  'KitchenCI',
  'Autify',
  'Sofy.ai',
  'Magneto',
  'BitBar',
  'CloudQA',
  'MuukTest',
  'Waldo',
  'TestGrid',
  'TestQuality',
  'aqua cloud',
  'DataTrust (formerly RDt)',
  'Mailosaur',
  'Meticulous',
  'Kobiton',
  'MOZARK',
  'Automai Robotic Automation Platform',
  'Litmus Chaos',
  'Micro Focus Silk Test',
  'QF-Test',
  'Delphix',
  'Rapise',
  'Repeato',
  'TestCraft by Perforce',
  'iCEDQ',
  'Micro Focus LoadRunner Enterprise',
  'Parasoft SOAtest',
  'Squish GUI Tester',
  'STAF',
  'Test Automation & Test Management Software',
  'Testinium',
  'UI-licious',
  'Applause',
  'Cerberus',
  'Karate Labs',
  'Qualitia',
  'Appsurify',
  'Appvance IQ',
  'CloudTestr - Continuous Test Automation Solution',
  'Cypress.io',
  'Everystep Scripting Tool',
  'ids',
  'QA Wizard Pro',
  'QMetry Automation Studio',
  'SeaLights',
  'Test.ai',
  'Testim',
  'Tricentis Neoload',
  'TurnKey Solutions',
  'UbikLoadPack',
  'WAPT Pro',
  'AREX Test',
  'AutomationHQ',
  'CA InterTest Batch',
  'Develocity',
  'devmate',
  'Doppelio',
  'Gauge',
  'IBM Rational Test Workbench',
  'Meeshkan',
  'NightwatchJS',
  'Orange Testing Platform',
  'Playwright',
  'QATTS',
  'Qunit',
  'Qyrus',
  'TestLeft',
  'TestResults.io',
  'TRAILBLU AI-powered Test Automation',
  'Z-automate',
  'Agilitest',
  'AgreeYa HuLoop',
  'aida smartest suite',
  'aiTest',
  'akaAT',
  'algoQA',
  'Alithya GoTest',
  'Apptimized Evergreen',
  'Aptori',
  'AquilaTest',
  'Assertology',
  'autoMagiQ',
  'Automate Data Testing',
  'Automaton',
  'AutonomIQ',
  'BELLATRIX',
  'BIValidator (2 Users)',
  'Blinq.IO',
  'BlueGem',
  'BMC Compuware Topaz for Total Test',
  'Boozang',
  'Capybara',
  'CARINA',
  'CDRouter',
  'Chasma Quale',
  'Comparium',
  'Cycle Labs',
  'DeploySentinel',
  'Diffblue Cover',
  'DigitalOnUs',
  'DoesQA',
  'DogQ',
  'Emtrey',
  'ETS',
  'Gridlastic',
  'Hamlex',
  'IBM Z Development and Test Environment',
  'Knapsack Pro',
  'Leankoala',
  'Microcks',
  'Micro Focus Business Process Testing',
  'Micro Focus Data Express',
  'Micro Focus DevPartner',
  'Micro Focus NetIQ Validator',
  'Moon',
  'Octoperf',
  'Parrot QA',
  'Pentest Collaboration Framework',
  'QARA Enterprise',
  'QRACE',
  'Qualibrate',
  'QualiDI',
  'Qualiti.AI',
  'Rakuten SixthSense Test Acceleration Platform',
  'Reflow',
  'SBOX',
  'Scandium',
  'Screener.io',
  'Speedchecker',
  'Squaretest',
  'STBSuite',
  'Step',
  'Tellurium',
  'Tenjin',
  'Tenjin Online',
  'Test Anywhere',
  'TestBench',
  'TestDrive',
  'Test Evolve - Agile Test Automation Solution',
  'TestingBot',
  'TestJet',
  'Testlum',
  'TestMagic',
  'TestMagic',
  'testOFFICE',
  'Tesults',
  'TheTestMart Automated Testing for Dynamics 365',
  'TimeShiftX',
  'T-Plan Trusted Business Automation',
  'Tricentis Test Automation',
  'Tricentis Test Automation for Salesforce',
  'UiPath Test Suite',
  'Verity',
  'Visual Integration Processor',
  'Wallaby.js',
  'Webomates CQ',
  'WinfoTest',
  'YEST',
  'Zebrunner',
  'Zeenyx AscentialTest',
];
