export const foundDirectCompetitors = [
  'LambdaTest',
  'Keysight Eggplant',
  'QA Wolf',
  'Provar',
  'Leapwork',
  'Opkey',
  'Rainforest QA',
  'Tricentis Tosca',
  'Sauce Labs',
  'Tricentis qTest',
  'Virtuoso',
  'Micro Focus UFT One',
  'Testsigma',
  'ContextQA',
  'SOAPUI',
  'TestStand',
  'testomat.io',
  'Qase',
  'Apache JMeter',
  'iMacros',
  'Perfecto',
  'Avo Assure',
  'Oracle Application Testing Suite',
  'Worksoft Certify',
  'Endtest',
  'TestComplete',
  'Tricentis Testim',
  'Ghost Inspector',
  'Reflect',
  'TestProject',
  'Functionize',
  'ACCELQ',
  'Micro Focus LoadRunner Professional',
  'QMetry Test Management',
  'ReadyAPI',
  'AutomatePro',
  'Micro Focus UFT Developer',
  'Telerik Test Studio',
  'SeeTest: Testing Platform for Web & Mobile Apps',
  'mabl',
  'Ranorex Studio',
  'HyperTest',
  'testRigor AI-powered Automation Testing Tool',
  'Subject7',
  'IBM Engineering Test Management',
  'TestingWhiz',
  'TestCafe',
  'ProdPerfect',
  'Zephyr Enterprise',
  'Autify',
  'Sofy.ai',
  'BitBar',
  'CloudQA',
  'MuukTest',
  'Waldo',
  'TestGrid',
  'TestQuality',
  'aqua cloud',
  'Kobiton',
  'Micro Focus Silk Test',
  'QF-Test',
  'Rapise',
  'TestCraft by Perforce',
  'Micro Focus LoadRunner Enterprise',
  'Parasoft SOAtest',
  'Squish GUI Tester',
  'Test Automation & Test Management Software',
  'Testinium',
  'Cypress.io',
  'ids',
  'QA Wizard Pro',
  'QMetry Automation Studio',
  'SeaLights',
  'Test.ai',
  'Testim',
  'Tricentis Neoload',
  'NightwatchJS',
  'Playwright',
  'TestLeft',
  'TestResults.io',
  'Agilitest',
  'AgreeYa HuLoop',
  'aiTest',
  'Apptimized Evergreen',
  'Assertology',
  'Automate Data Testing',
  'AutonomIQ',
  'BELLATRIX',
  'Blinq.IO',
  'Boozang',
  'Capybara',
  'CARINA',
  'CDRouter',
  'Comparium',
  'Diffblue Cover',
  'Hammer On-Demand',
  'IBM Z Development and Test Environment',
  'Micro Focus Business Process Testing',
  'Micro Focus DevPartner',
  'Octoperf',
  'QARA Enterprise',
  'Qualibrate',
  'Reflow',
  'Screener.io',
  'Speedchecker',
  'STBSuite',
  'Test Anywhere',
  'TestBench',
  'TestDrive',
  'Test Evolve - Agile Test Automation Solution',
  'TestingBot',
  'TestJet',
  'testOFFICE',
  'Tesults',
  'TimeShiftX',
  'T-Plan Trusted Business Automation',
  'Tricentis Test Automation',
  'Tricentis Test Automation for Salesforce',
  'UiPath Test Suite',
  'Verity',
  'Wallaby.js',
  'Webomates CQ',
  'Zeenyx AscentialTest',
];
