export const foundCompetitors = [
  'LambdaTest',
  'Testsigma',
  'Testpine',
  'Reflect',
  'Conektto API Test Harness',
  'LoadFocus',
  'testRigor',
  'CodiumAI',
  'ACCELQ',
  'Testfly',
  'Loadero',
  'MagicPod',
  'Karate Labs',
  'Vedro',
  'Automize',
  'Surfsky Browser Automation in the Cloud',
  'TestingBot',
  'TestX',
  'SimpleApiTest',
  'Automation Flow',
  'reqInspect',
  'apiJest',
  'EpicQA',
];
