export const foundTestingTools = [
  'LambdaTest',
  'Waldo Testing',
  'Ponicode Unit Test',
  'PreFlight',
  'Relicx',
  'Testsigma',
  'Testpine',
  'Deepchecks: Continuous Validation for AI',
  'Reflect',
  'Conektto API Test Harness',
  'LoadFocus',
  'Mobile FIRST',
  'testRigor',
  'Does QA',
  'CodiumAI',
  'DebugBear',
  'ACCELQ',
  'Testfly',
  'Schema Validator Browser Extension',
  'DeepUnit',
  'Loadero',
  'Load-test.io',
  'MagicPod',
  'Karate Labs',
  'EazyMock',
  'Vedro',
  'Automize',
  'SMTP Debug Tool',
  'DVC Extension for VS Code',
  'NativeRest',
  'Supertest',
  'Kreya',
  'Automock',
  'JSON Web Token (JWT) Debugger',
  'Surfsky Browser Automation in the Cloud',
  'OpenGraph Preview by ImageBinary',
  'TestingBot',
  'TestX',
  'SimpleApiTest',
  'drf-api-action',
  'The SCIM Playground',
  'Cookie-Editor',
  'OpenAI Tools',
  'Cookie Scanner',
  'Automation Flow',
  'reqInspect',
  'apiJest',
  'API for product managers and QAs',
  'Artemis',
  'Mayhem',
  'EpicQA',
  'PSRule.Rules.AzureDevOps',
];
